### ISSUE TITLE
Can't create a new plugin-sdk project in Code::Blocks

### ISSUE THREAD

**Issue by chaitanyathengdi** [DK22Pac/plugin-sdk#104]
I built the plugin project, set all the values as indicated in the wiki in the installer, and tried to create a new project.

But I can't actually create a new project; the page is blank.
![image](https://user-images.githubusercontent.com/14993220/100478770-39926580-3112-11eb-9262-aa9068955881.png)
If I click next, I can't:
![image](https://user-images.githubusercontent.com/14993220/100478786-4adb7200-3112-11eb-87ab-ce12f134c829.png)

I'm only going to develop plugins for San Andreas.

At the moment, I have to rely on modifying existing examples given in the examples/ sub directory to make plugins.

Some info:
OS: Windows 7 x64 SP1
IDE: Code::Blocks 20.03
gcc: 7.2.0(as per mingw-w64)
DirectX SDK: DirectX 9 (June 2010)

**Comment by user-grinch** [comment]
Remove the 7th line from this file (CodeBlocks)\templates\wizard\pluginsdk\wizard.xrc
`<rows>2</rows>`

**Comment by chaitanyathengdi** [comment]
@user-grinch Worked! Thanks.
