### ISSUE TITLE
Is it possible to remove events?

### ISSUE THREAD

**Issue by crwn1337** [DK22Pac/plugin-sdk#109]
For example:
```
plugin::Events::gameProcessEvent += [] {
	Command<Commands::PRINT_NOW>("IN_VEH", 150, 0);
};
```

and then somewhere later remove the event?

**Comment by Megasware128** [comment]
Not really sure about C++ but in .NET you would `-=` to remove an event. You could try putting the lamda in a variable then use `+=` and `-=`. Purely a theoretical suggestion, haven't tried in practice.

**Comment by crwn1337** [comment]
It does work!

For future reference:
```
void process() {
	if (plugin::Command<plugin::Commands::IS_PLAYER_PLAYING>(0)) {
		plugin::Command<plugin::Commands::PRINT_NOW>("IN_VEH", 150, 0);
	}
}

plugin::Events::processScriptsEvent += process; // add it
plugin::Events::processScriptsEvent -= process; // remove it
```

**Comment by Megasware128** [comment]
Ah yes, I was overthinking it needing to put a lambda in a variable. Making a function as a much simpler solution 😅

**Comment by Megasware128** [comment]
Ah yes, I was overthinking it needing to put a lambda in a variable. Making a function as a much simpler solution 😅
