### ISSUE TITLE
problem build

### ISSUE THREAD

**Issue by UEEVEEN** [DK22Pac/plugin-sdk#112]
![image](https://user-images.githubusercontent.com/69657648/108759860-95c02680-7555-11eb-9d38-a65b71a9c30a.png)

**Comment by user-grinch** [comment]
Build Plugin SDK 
[here](https://github.com/DK22Pac/plugin-sdk/wiki/Set-up-plugin-sdk)

**Comment by UEEVEEN** [comment]
-
