### ISSUE TITLE
Wasted wiki page with last two revisions

### ISSUE THREAD

**Issue by ShaggE** [DK22Pac/plugin-sdk#115]
https://github.com/DK22Pac/plugin-sdk/wiki/Creating-a-new-plugin-in-plugin-sdk
I don't know the better way to restore old revision by DK

**Comment by Izzotop** [comment]
I [rolled back](https://docs.github.com/en/github/building-a-strong-community/viewing-a-wikis-history-of-changes#reverting-previous-changes) the changes.

**Comment by ShaggE** [comment]
Wow, thank you! I didn't know about this function
