### ISSUE TITLE
trying to get pitch from CCamera.h

### ISSUE THREAD

**Issue by Frouk3** [DK22Pac/plugin-sdk#129]
i can't find camera pitch(for airbrake)

**Comment by gennariarmando** [comment]
`TheCamera.m_aCams[TheCamera.m_nActiveCam].m_fVerticalAngle`
`TheCamera.m_aCams[TheCamera.m_nActiveCam].m_fHorizontalAngle`

**Comment by Frouk3** [comment]
ty
