### ISSUE TITLE
The link for the eblip colors in CRadar.h doesn't work anymore.

### ISSUE THREAD

**Issue by juicermv** [DK22Pac/plugin-sdk#149]
Hi, I'm looking for the RGB color values of the 8 blip colors but [the link](https://www.dropbox.com/s/oi3i4f0qsbe7z10/blip_marker_colors.html) doesn't work anymore. Could anyone please provide this here and perhaps update that link? Thanks.

**Comment by JuniorDjjr** [comment]
`CRadar::GetRadarTraceColour 0x584770`
A bit complex. It does a conversion of the blip color id (also considering a flag) to the game's color palette (the same color palette used for fonts etc).

**Comment by juicermv** [comment]
Yeah thanks, I already figured this out but forgot I opened this issue in the first place lol. The only issue with this function is that some destination blips are not normally colored meaning they might be blue or red instead of the usual yellow, but this function always returns the default yellow for destinations. Either way I'm marking this as closed.
