### ISSUE TITLE
Error while compiling script (C3861 'M_PI': identifier not found) [Visual Studio 2019]

### ISSUE THREAD

**Issue by kozooh** [DK22Pac/plugin-sdk#153]
I tried to compile script for Vice City with Visual Studio 2019 but always got these two errors.

`Error	C3861	'M_PI': identifier not found	CustomColorsVC	D:\Pobrane\plugin-sdk-master\shared\Other.h	70	`
`Error	C3861	'M_PI': identifier not found	CustomColorsVC	D:\Pobrane\plugin-sdk-master\shared\Other.h	75	`

Here's the script which is actually based on this DK22Pacs [post](https://gtaforums.com/topic/117195-documenting-gta3vc-memory-addresses/?do=findComment&comment=1069380274)

```
#include "plugin.h"

using namespace plugin;

class CustomColorsVC {
public:
    CustomColorsVC() { 
        patch::SetUChar(0x5582AF, 0);  // Money color : Red
        patch::SetUInt(0x5582AA, 122); // Money color : Green
        patch::SetUInt(0x5582A5, 204); // Money color : Blue
    }
} CustomColorsVC;
```

I know that is just a constant PI value. But in the header file so I don't know what to do with it. I just blindly add include <cmath> etc. libraries but without results.

Yes, I've installed plugin-sdk with instruction.

**Comment by cengizhanbucak** [comment]
most likely I have the same problem related to windows 11 dirext

**Comment by nekjutsu** [comment]
Add _USE_MATH_DEFINES to preprocessor definitions

**Comment by kozooh** [comment]
> Add _USE_MATH_DEFINES to preprocessor definitions

Thanks
