### ISSUE TITLE
Build errors caused by C/C++ preprocessor definitions

### ISSUE THREAD

**Issue by ChaseOne1** [DK22Pac/plugin-sdk#160]
When I try to build the plugin_sa solution, VS2019 warns me that the identifier M_PI cannot be found in shared\Other.h (error C3861);
After trying, I added "_USE_MATH_DEFINES" to the C/C++ precompiler of the project in VS, and then the build was successful.

**Comment by Vladik01-11** [comment]
https://github.com/DK22Pac/plugin-sdk/issues/153

**Comment by Vladik01-11** [comment]
All I can say as a person who has faced this problem, it appeared with the commit of adding GTA 2 (https://github.com/DK22Pac/plugin-sdk/commit/242a3e31ea737b6ab2bf08c3564583954f25ccaf#diff-273bd764e52fb9f947248b516839a840cc639a1c42d2e6317af9016a25dc98aa) and another person has already faced this problem (https://github.com/DK22Pac/plugin-sdk/issues/153)
