### ISSUE TITLE
VSIX installer error in Visual Studio

### ISSUE THREAD

**Issue by pblro** [DK22Pac/plugin-sdk#165]
Hello, I just can't install the template in my Visual Studio, I use VS 2017 Enterprise version 15.0, I also have the same error in Visual Studio 2022 Community. I've even reformatted my windows, installed NET Framework 2, 3 and 4, all the 'Visual C++ Redist' in my OS (Windows 10 Pro), before I could and even made several complete mods, but after formatting Windows I get this error.

"The extension cannot be installed to this product due to prerequisites that cannot be resolved."

![image search api](https://i.imgur.com/hVaZE9e.png)

**Comment by gennariarmando** [comment]
Hi, Visual Studio templates are deprecated and will not be supported anymore.
Premake templates will instead be soon added for each game, which can be then easily edited to create project files.

**Comment by TheArtemMaps** [comment]
> Hi, Visual Studio templates are deprecated and will not be supported anymore. Premake templates will instead be soon added for each game, which can be then easily edited to create project files.

check my pull request, since you have rights to do commits immediately

**Comment by pblro** [comment]
I managed to solve this specific problem just by installing it on another system, but I can't say what could have caused this, perhaps the system's resources were corrupted, since it was a modified system.

And when I installed it in Visual Studio I received the same error as: #88
