### ISSUE TITLE
Error in plugin gen

### ISSUE THREAD

**Issue by shpeenut22** [DK22Pac/plugin-sdk#180]
The system cannot find the specified path
![Снимок экрана (37)](https://github.com/DK22Pac/plugin-sdk/assets/102990674/7a9654fa-da21-47dd-a9a4-f5b9b3737d97)

**Comment by Hiteke** [comment]
Запусти `Generate MyPlugin.bat` из папки `tools/myplugin-gen`

**Comment by shpeenut22** [comment]
> Запусти `Generate MyPlugin.bat` из папки `tools/myplugin-gen`

он создает решение, но сбилдить его не получается, он не видит .lib файл

**Comment by TheArtemMaps** [comment]
> > Запусти `Generate MyPlugin.bat` из папки `tools/myplugin-gen`
> 
> он создает решение, но сбилдить его не получается, он не видит .lib файл

Собери решение plugin-sdk

**Comment by shpeenut22** [comment]
> > > Запусти `Generate MyPlugin.bat` из папки `tools/myplugin-gen`
> > 
> > 
> > он создает решение, но сбилдить его не получается, он не видит .lib файл
> 
> Собери решение plugin-sdk, в двух решимаж (Release, zDebug).

ох, как я мог об этом забыть.
Все работает, спасибо.
