### ISSUE TITLE
Are D3D9Headers really necessary?

### ISSUE THREAD

**Issue by thelink2012** [DK22Pac/plugin-sdk#2]
This involves using Microsoft copyrighted headers, this doesn't look OK on redistributing those.
If the user wants to use D3D9 Headers, let him take care of it, besides, the necessary headers for complete RW header comes with most compilers.

So, my suggestion is to remove those headers from the project and assume they're installed on the target machine (as they probably are). There's also a define there to use or not to use D3D9 headers, you see, really, remove those goddamn Microsoft headers!

**Comment by quiret** [comment]
I don't think Microsoft would care. Maybe those headers come for legacy support, in case Microsoft will ever scrap this deprecated technology from their SDK. ^^
