### ISSUE TITLE
LINK1104: cannot open file 'plugin_d.lib'

### ISSUE THREAD

**Issue by Temoto-kun** [DK22Pac/plugin-sdk#23]
How to resolve this is not written in the documentation.

It just happens that the `plugin_d.lib` file is just written in the project linker config as is (without a complete path).

**Comment by quiret** [comment]
Have you compiled plugin_sa and plugin_vc in Debug configuration? Compiling them this way creates the files in the right spot :)

Could you specify what project you were compiling? Any of the examples?

**Comment by bengace** [comment]
I had the same problem, as quiret said above you have to open the plugin.sln in the root directory and build either the SA or the VC plugin project and it will create the plugin_d.lib file, after that your plugins will compile just fine.

**Comment by Temoto-kun** [comment]
@quiret, @bengace Your solution worked. I just need to compile the plugin_sa/plugin_vc project. I didn't know this had to be done because it wasn't included in the installation instructions in the wiki.

Closing this now.
