### ISSUE TITLE
CPool allocation ownership

### ISSUE THREAD

**Issue by CookiePLMonster** [DK22Pac/plugin-sdk#24]
https://github.com/DK22Pac/plugin-sdk/blob/8dd5292b893868c35158bf7fc9fcf6a3a8d9756d/plugin_sa/game_sa/CPool.h#L68

This should be false! Apparently my own issue from years back :(

EDIT:
Also shouldn't allocate memory by itself but rather just assign the ones passed to the function - hence they don't "take ownership" of these allocations.

**Comment by quiret** [comment]
The content of the function does not match documented-by-comment behavior. Good catch, case of the wrong copy paste? ^^

**Comment by CookiePLMonster** [comment]
Probably so, yes. I am sure this is wrong since I remember stock SA function well - must have a failure on my end when commiting that.

**Comment by quiret** [comment]
I have just committed a patch for that function, how I imagine it should work. Do you agree with the change?

**Comment by CookiePLMonster** [comment]
I'm not 100% sure if deletion at Init time is safe - are these fields ensured to be initialized at construction time? If so, it looks OK.

operator delete can be called on a null pointer btw.

**Comment by quiret** [comment]
Good point. We are being very hypothetic anyway because reimplementation is not the goal of plugin-sdk anyway, I think. :)

The latest commit should fit the bill.

**Comment by CookiePLMonster** [comment]
Yep! Good stuff!
