### ISSUE TITLE
LNK1181: эх єфрхЄё  юЄъЁ√Є№ тїюфэющ Їрщы "paths_d.lib"

### ISSUE THREAD

**Issue by BloodTiger** [DK22Pac/plugin-sdk#25]
When i trying to compile "plugin_sa" i am getting this weird error. "plugin_vc" compiled without any problems, but "plugin_sa"..
![2017-02-09_13-24-09](https://cloud.githubusercontent.com/assets/25642045/22779266/15bab92e-eecb-11e6-88f2-9b1cfc31a8b7.png)

**Comment by DK22Pac** [comment]
1) Update your plugin-sdk repository.
2) Try to build it again.

If this won't help, do this:
1) RMB on plugin_sa project in Solution Explorer
2) Build Dependencies > Project Dependencies

![Img1](http://i.imgur.com/JCwTsL1.png)

3) Check if you have "paths" and "config" checked:

![Img2](http://i.imgur.com/SVMTJk6.png)

4) If you have them checked and still can't compile plugin_sa project, try to build them (projects "shared/paths" and "shared/config") manually.

Also, in most cases you should use Release version of plugin-sdk. You can build both versions by switching build mode here:

![Img3](http://i.imgur.com/a7tBjTE.png)

First, build plugin_sa in Release mode (plugin.lib), then switch mode to Debug and build again (plugin_d.lib).

**Comment by BloodTiger** [comment]
Thanks! Problem has gone.

**Comment by MIckromax** [comment]
I have this error while compiling a project with the plugin sdk, reinstalled VS and plugin-sdk, can anyone recommend what I should do?
