### ISSUE TITLE
I can't build My Project

### ISSUE THREAD

**Issue by XKangs** [DK22Pac/plugin-sdk#27]
I have created a new Vice City .Asi project, and I Press F5 to build this new project, then VS throw a error 
LNK1181	cannot open input file 'plugin_vc.lib'	Project2	c:\Users\XXX\documents\visual studio 2015\Projects\Project2\Project2\LINK	1	
build configurations is rel

**Comment by XKangs** [comment]
it is a new project it means I don't write anything in it

**Comment by DK22Pac** [comment]
You need to build plugin_sa and plugin_vc projects before.
Open plugin-sdk solution and build it.
