### ISSUE TITLE
Visual Studio 2017?

### ISSUE THREAD

**Issue by quiret** [DK22Pac/plugin-sdk#29]
Should we move to the new compiler/toolset?

Also what about the state of the three "tags" of plugin-sdk? Two are owned by LINK/2012, one of is DK22Pac. LINK's date to 2014. Can we clean up?

**Comment by DK22Pac** [comment]
We'll move, but later.

Yes, we can.

**Comment by quiret** [comment]
Thanks. Should reduce DL size of SVN checkout.
