### ISSUE TITLE
Missing plugin_d.lib

### ISSUE THREAD

**Issue by Kewun0** [DK22Pac/plugin-sdk#30]
As in title. I get that error

**Comment by quiret** [comment]
Hello Kewun0!

Your issue sounds similar to https://github.com/DK22Pac/plugin-sdk/issues/23
Solution was to find "plugin.sln" and compile in Debug configuration, for you I think plugin_sa.

If it does not solve your problem, could you elaborate further?

**Comment by Kewun0** [comment]
Already fixed, but now getting other shitton load of errors. unresolved symbols, etc
example : 
1. http://imgur.com/a/M1dJs
2. http://imgur.com/a/U40Jk

**Comment by quiret** [comment]
In plugin-sdk you have to include headers that you need.

https://github.com/DK22Pac/plugin-sdk/blob/master/plugin_III/game_III/CPlayerPed.h

Try doing: #include "game_III/CPlayerPed.h"

**Comment by Kewun0** [comment]
errors

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CEntity.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CEntity.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CMatrix.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CMatrix.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CPhysical.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CPhysical.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CPlaceable.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CPlaceable.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CPlayerPed.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in Main.obj	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III.lib(CPlayerPed.obj)	1	
Error	LNK1319	10 mismatches detected	Project1	D:\Grand Theft Auto III\plugins\Project1_d.asi	1	

`

**Comment by Kewun0** [comment]
#include "plugin_III.h"
#include "game_III/CPlayerPed.h"
using namespace plugin;

class MyPlugin {
public:
    MyPlugin() {
		if (KeyPressed(VK_SHIFT))
		{
			CPlayerPed Player;
			Player.Remove();
		}
    }
} myPlugin;

**Comment by ifarbod** [comment]
Could you at least use Markdown blocks to format your code? It looks ugly and hard to read.

Something like this:
```cpp
void Test() { return; }
```

**Comment by quiret** [comment]
Btw, have you tried using the plugin-sdk project wizard inside the "tools" folder? It is very useful, because you get many templates in Visual Studio :)

![image](https://cloud.githubusercontent.com/assets/7682485/25072447/8c66246e-22ce-11e7-913d-46f02f28fed3.png)

![image](https://cloud.githubusercontent.com/assets/7682485/25072439/5908da9e-22ce-11e7-9901-f575f0732acd.png)

To fix your problem please change the runtime library setting in your project, like

![image](https://cloud.githubusercontent.com/assets/7682485/25072449/9a6bc262-22ce-11e7-9466-ae8d4720b8f4.png)

**Comment by Kewun0** [comment]
i used the wizard, also the settings are same as in your screenshot.

**Comment by quiret** [comment]
Sorry for the inconvenience! There is a small bug in the wizard. Please change this setting:

![image](https://cloud.githubusercontent.com/assets/7682485/25072522/918eed52-22d0-11e7-99ab-6bee83aa059a.png)

**Comment by Kewun0** [comment]
same errors...

**Comment by quiret** [comment]
Are you sure? Please post the error log again. I would like to take a look at it.

**Comment by Kewun0** [comment]
https://pastebin.com/wtCea7wX

**Comment by quiret** [comment]
Your log says it uses "plugin_III.lib". Are you sure you changed library to "plugin_III_d.lib"?

**Comment by Kewun0** [comment]
yes. http://imgur.com/a/ky7vi

**Comment by quiret** [comment]
Please try changing the Configuration to Debug and try again
![image](https://cloud.githubusercontent.com/assets/7682485/25072555/b8e0fd04-22d1-11e7-86fc-27d2a55f20d3.png)

**Comment by Kewun0** [comment]
Now i get only the error as in title, missing plugin_iii_d.lib
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'plugin_III_d.lib'	Project1	C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\LINK	1

**Comment by quiret** [comment]
Open plugin-sln and build the "plugin_III" project in Debug mode.
![image](https://cloud.githubusercontent.com/assets/7682485/25072591/8bbac7dc-22d2-11e7-8ee5-d284fb028266.png)

**Comment by Kewun0** [comment]
Done, and changed, now when i try build
https://pastebin.com/ZHr5QCA0

**Comment by quiret** [comment]
I have several questions to you.
- you seem to have a plugin-sdk lib here: C:\Users\Dom\Documents\Visual Studio 2017\Projects\Project1\Project1\plugin_III_d.lib
  This is not the default plugin-sdk folder, yes? Have you updated this file with the correct version? This does not look like a wizard-created project.
- Have you changed back the "plugin_III_d.lib" in Release configuration to "plugin_III.lib"?

**Comment by Kewun0** [comment]
1. yes, updated, and is wizard created project
2. no

**Comment by quiret** [comment]
2. then please try :)

**Comment by Kewun0** [comment]
Same errors

**Comment by quiret** [comment]
I have assigned DK22Pac to this issue. I hope this issue with project-wiazard will be fixed. I suggest you wait till he is here ;-)

Or you carefully check that you changed everything properly, again.

**Comment by DK22Pac** [comment]
Please follow these steps:
1. Download or update your plugin-sdk folder with latest changes.
2. Open `plugin-sdk\plugin.sln` and build solution in Release and Debug mode.
2. Close Visual Studio
3. Go to `Documents\Visual Studio 2017\Templates\ProjectTemplates` and delete `Plugin-SDK` folder there.
4. Open Command Prompt for VS2017 and run this command: `devenv /installvstemplates`
5. Open `plugin-sdk\tools\plugin-sdk-project-wizard\plugin-sdk-project-wizard.exe`, setup it and press `Generate`
6. Open Command Prompt for VS2017 and run this command: `devenv /installvstemplates`
7. Open Visual Studio and create a new project.

**Comment by Kewun0** [comment]
everything done, still this annoying error plugin_iii.lib cant open

**Comment by DK22Pac** [comment]
It looks like Visual Studio still loads old templates from cache.
And about your code, it doesn't correct.
You should add everything you want to do with peds/vehicles into gameProcessEvent, for example:
```cpp
#include "plugin_III.h"
#include "game_III\common.h"

using namespace plugin;

class MyPlugin {
public:
    MyPlugin() {
		Events::gameProcessEvent += [] {
			CPed *playa = FindPlayerPed();
			if (playa && KeyPressed(VK_F6)) {
				playa->m_fHealth += 1.0f;
			}
		};
    }
} myPlugin;
```
And also, developing of plugin-sdk for GTA III is just started, so there's not much you can do with it at this moment.

**Comment by Kewun0** [comment]
This needs documentation ;/

**Comment by Kewun0** [comment]
after your solution
http://imgur.com/a/zxISg

**Comment by Kewun0** [comment]
..

**Comment by Kewun0** [comment]
fixed every error, but  
`#include "plugin_III.h"
#include "game_III\common.h"

using namespace plugin;

class MyPlugin {
public:
    MyPlugin() {
        Events::gameProcessEvent += [] {
            CPed *playa = FindPlayerPed();
            if (playa && KeyPressed(VK_F6)) {
                playa->m_fHealth += 1.0f;
            }
        };
    }
} myPlugin;`

doesnt work, i press F6, and i dont get +1 health

**Comment by Kewun0** [comment]
Now i know why, this doesnt work on gta 3 1.1 ...

**Comment by DK22Pac** [comment]
We support only exe 1.0 version.
