### ISSUE TITLE
Wrapper for opcodes is missing

### ISSUE THREAD

**Issue by goodidea82** [DK22Pac/plugin-sdk#34]
Some earlier version had a wrapper (SCMWrapper) for opcodes (developed by fastman92), but now the API is missing:
https://github.com/DK22Pac/plugin-sdk/blob/master/src/sdk/plugin/script/wrapper.h
This API is important for because I already have a lot of custom code that depend on it. 

(Some background: http://gtaforums.com/topic/838490-cleo-plugin-how-to-call-an-opcode-within-a-cleo-plugin/?p=1068513051)

**Comment by DK22Pac** [comment]
It's possible to "call" an opcode in this way:
```cpp
using namespace plugin::test;
// ...
ScriptCommand<PRINT_NOW>("FEC_INC", 150, 1);
```
```cpp
#include "plugin_III.h"
#include "extensions\ScriptCommands.h"

using namespace plugin;
using namespace plugin::test;

class Gta3ScriptCommandsTest {
public:
    Gta3ScriptCommandsTest() {
        Events::processScriptsEvent += [] {

            int PlayerChar, PlayerCar;
            float CoordX, CoordY, CoordZ;

            if (ScriptCommand<IS_PLAYER_PLAYING>(0))
            {
                ScriptCommand<GET_PLAYER_CHAR>(0, &PlayerChar);
                if (ScriptCommand<IS_CHAR_IN_ANY_CAR>(PlayerChar))
                {
                    ScriptCommand<STORE_CAR_CHAR_IS_IN_NO_SAVE>(PlayerChar, &PlayerCar);
                    ScriptCommand<GET_CAR_COORDINATES>(PlayerCar, &CoordX, &CoordY, &CoordZ);
                    ScriptCommand<DRAW_SHADOW>(3, CoordX, CoordY, CoordZ, 0.0f, 3.0f, 150, 255, 0, 0);
                    ScriptCommand<PRINT_NOW>("FEC_INC", 150, 1);
                }
            }
        };
    }
} test;
```

**Comment by goodidea82** [comment]
Thanks for the quick reply.
I have a special use case where wrapper functions are automatically generated for opcodes.

Can I use hex-numbers instead of opcode names? E.g.
ScriptCommand< 0x00AA >(PlayerCar, &CoordX, &CoordY, &CoordZ);

I want the called opcode have the same effect on the current thread as a normal opcode would have. How do I pass the thread-pointer to the ScriptCommand? (or obtain a thread pointer if it has its own thread)  In my code I have a function "copyThreadAttrToWrapper" that translates the state from the current thread to the fastman's SCMwrapper's thread and "copyWrapperToThread" to translate it back.

Here is an example of what I mean:

void op00A0(DWORD actHandle1, float& varX2, float& varY3, float& varZ4){
    SCMwrapper.PushInt(actHandle1, true);
    SCMwrapper.PushFloat(varX2, true);
    SCMwrapper.PushFloat(varY3, true);
    SCMwrapper.PushFloat(varZ4, true);
    copyThreadAttrToWrapper(curThread, SCMwrapper, (curThread->notFlag? 0x80A0: 0x00A0));
    cmdResult =  SCMwrapper.CallCommand(curThread->notFlag? 0x80A0: 0x00A0);
    copyWrapperToThread(SCMwrapper, curThread);
    SCMwrapper.SaveReturnedValues(retVal);
    varX2 = varX(retVal.returnedValues[1].Float);
    varY3 = varY(retVal.returnedValues[2].Float);
    varZ4 = varZ(retVal.returnedValues[3].Float);
}


The easiest for me would be if fastman's SCMwrapper API would be added back.

**Comment by DK22Pac** [comment]
> Can I use hex-numbers instead of opcode names?
Yes.
> Do I need the "Events::processScriptsEvent += [] {...}" to call an opcode and what does it mean?
It's recommended to 'call' opcodes when scripts are 'processed' (i.e. executed). That's why processScriptsEvent event is used in this example.
> How do I pass the thread-pointer to the ScriptCommand?
Not possible yet.

**Comment by goodidea82** [comment]
I have copied this thread here: [http://gtaforums.com/topic/838490-cleo-plugin-how-to-call-an-opcode-within-a-cleo-plugin/?p=1069733231](url)
because I don't know where to find again it when the issue is closed.
