### ISSUE TITLE
Please vote! Should we use environment variables?

### ISSUE THREAD

**Issue by DK22Pac** [DK22Pac/plugin-sdk#36]
I'm going to update template generator for projects, and seriously thought about the possibility of using **environment variables**.

Should we use them for plugin-sdk projects? They can be used to determine the location of

- CLEO SDK
- DirectX SDK
- GTA scripts
- GTA cleo

directories.

It'll make it possible to use and compile plugin-sdk projects on different computers without any problems, without additional configuration of paths in project options.

What do you think?

**Comment by Megasware128** [comment]
I'm already doing this in a fork of mine because of this. I would vote for yes

**Comment by quiret** [comment]
Good idea! Initial content of variables should be set in template generator and it should mention that special environment variables are added.

**Comment by DK22Pac** [comment]
Thanks everyone.
**Resolved:** we will use global variables for Plugin-SDK, GTA ASI/CLEO, CLEO SDK and DirectX SDK folders.
I will integrate this into new **plugin-sdk project wizard**. You could change paths for every project (i.e. it be changeable when you create a project), but they will be set to global variables by default.
![wizard1](https://user-images.githubusercontent.com/6964404/28644537-a1f9ad80-7262-11e7-9a2a-b705f68ff3a9.PNG)

**Comment by quiret** [comment]
Has this been integrated into the plugin-sdk project wizard yet? I see no "Advanced Settings" option there:
![project_wizard_adv_settings_notfound](https://user-images.githubusercontent.com/7682485/30239319-47e03e48-955a-11e7-96da-b183ee0d9029.png)
It could help a lot to have a configuration tool instead of manually changing environment variables.

**Comment by DK22Pac** [comment]
No, it's not integrated yet.
With new wizard, you could set custom paths for everything (except plugin-sdk location - it must be an environment variable in any case) - for example, you could specify target directory (instead of using `GTA_*_ASI_DIR`)
And for changing environment variables - yes, maybe another tool would be helpful.

**Comment by quiret** [comment]
There now is a tool called "psdk_config.exe" in the repository that automatically scans for plugin-sdk folders and sets the correct environment variables if it finds them. Maybe the tool can be updated to be GUI based (currently console only).
