### ISSUE TITLE
strcpy issue

### ISSUE THREAD

**Issue by ThirteenAG** [DK22Pac/plugin-sdk#37]
https://github.com/DK22Pac/plugin-sdk/blob/master/plugin_III/extensions/ScriptCommands.h#L75
V512 A call of the 'strcpy' function will lead to overflow of the buffer 'script.m_szName'. scriptcommands.h 75

**Comment by quiret** [comment]
Fixed in https://github.com/DK22Pac/plugin-sdk/commit/49ff44bd8e3e54b3294d1524f1802ec09fcc8df7 .
Could you verify and close this issue? :)
