### ISSUE TITLE
How to target multiple games in one solution?

### ISSUE THREAD

**Issue by Temoto-kun** [DK22Pac/plugin-sdk#39]
I tried copying project settings for each game into a single project with different build settings corresponding to each game (III, VC, SA). No luck because Visual Studio can't find the include files. How can I be able to accomplish this?

**Comment by DK22Pac** [comment]
Only in manual way.
This will be possible in next plugin-sdk version though.

**Comment by DK22Pac** [comment]
Our new Project Wizard for Code::Blocks and Visual Studio 2015/2017 can target multiple games.
