### ISSUE TITLE
KeyPressed not working for vc?

### ISSUE THREAD

**Issue by Kewun0** [DK22Pac/plugin-sdk#40]
`#include "plugin_vc.h"
#include "game_vc/CDraw.h"
#include "game_vc/CWeapon.h"
#include "game_vc/CPed.h"
#include "game_vc/CPlayerPed.h"
#include "game_vc/eWeaponType.h"
using namespace plugin;

class MyPlugin {
public:
    MyPlugin() {
		MessageBeep(true);
		
		if (KeyPressed(VK_F9))
		{
			MessageBeep(true);
			MessageBoxA(NULL, "LOL", "LOL", 0);
			CPlayerPed twojstary;
			twojstary.m_fArmour = 125.0;
			twojstary.GiveWeapon(WEAPONTYPE_M4, 9999, false);
			twojstary.GiveWeapon(WEAPONTYPE_MP5, 9999, false);
			MessageBeep(true);
		}
    }
} myPlugin;`

No errors during compile, i get beep when plugin gets loaded, i press F9, nothing happens. Why ? 

Edit: ok fixed, forgot processgame event, but now the player doesnt get armour and weapons, why?

**Comment by gennariarmando** [comment]
Try this:

`
#include "plugin_vc.h"
#include "game_vc\common.h"
#include "game_vc/CDraw.h"
#include "game_vc/CWeapon.h"
#include "game_vc/CPed.h"
#include "game_vc/CPlayerPed.h"
#include "game_vc/eWeaponType.h"
using namespace plugin;

class MyPlugin {
public:
    MyPlugin() {
        MessageBeep(true);

        if (KeyPressed(VK_F9))
        {
            MessageBeep(true);
            MessageBoxA(NULL, "LOL", "LOL", 0);
            CPed * twojstary = FindPlayerPed();
            twojstary->m_fArmour = 125.0;
            twojstary->GiveWeapon(WEAPONTYPE_M4, 9999, false);
            twojstary->GiveWeapon(WEAPONTYPE_MP5, 9999, false);
            MessageBeep(true);
        }
    }
} myPlugin;
`

**Comment by Kewun0** [comment]
this seems to work, thanks for the help. Never trought CPlayerPed isnt local player
