### ISSUE TITLE
Is there GetClosestEntity or FindClosestPed() ?

### ISSUE THREAD

**Issue by Kewun0** [DK22Pac/plugin-sdk#41]
As in title, is there something like that? ( for vc )
Also what are eMoveState params?
I want for example, get the closest ped near me, if there exist, then kills the ped

**Comment by DK22Pac** [comment]
No, but there's [m_apNearPeds](https://github.com/DK22Pac/plugin-sdk/blob/master/plugin_vc/game_vc/CPed.h#L309) array in CPed struct.

**Comment by Kewun0** [comment]
okay so 
`   
    CPed * gracz = FindPlayerPed();
			else if (KeyPressed(VK_RBUTTON))
			{
				if (!gracz->m_apNearPeds[0] && !gracz->m_apNearPeds[1] && !gracz->m_apNearPeds[2] && !gracz->m_apNearPeds[3] && !gracz->m_apNearPeds[4] && !gracz->m_apNearPeds[5] && !gracz->m_apNearPeds[6] && !gracz->m_apNearPeds[7] && !gracz->m_apNearPeds[8] && !gracz->m_apNearPeds[9] && !gracz->m_apNearPeds[10]) { return; }
				if (gracz->m_apNearPeds[0]->m_fHealth != 0.0 && gracz->m_apNearPeds[0]->IsPedShootable() && gracz->m_apNearPeds[0]->IsVisible())
				{
					if (gracz->m_apNearPeds[0])
					{
						gracz->m_pPointGunAt = gracz->m_apNearPeds[0];
						gracz->AimGun();
						gracz->Attack();
						gracz->ClearAttackByRemovingAnim();
						return;
					}
				}
                   }
`

Im trying to do something 'alike' aimassist , but i cant aim the gun correctly at the nearest ped. The game sometimes even crashes
https://www.youtube.com/watch?v=7iXgxrbE7E0
Here you see how it looks weirdly
Could you help me out fixing the code? ;/

**Comment by DK22Pac** [comment]
```cpp
static CPed *GetNearestPed(CPed *ped) {
    CPed *nearestPed = nullptr;
    float nearestDistance = 9999.0f;
    for (int i = 0; i < 10; i++) {
        if (ped->m_apNearPeds[i]) {
            float distance = DistanceBetweenPoints(ped->GetPosition(), ped->m_apNearPeds[i]->GetPosition());
            if (distance < nearestDistance) {
                nearestPed = ped->m_apNearPeds[i];
                nearestDistance = distance;
            }
        }
    }
    return nearestPed;
}
```

**Comment by Kewun0** [comment]
So it crashes because the m_apNearPed fails?
