### ISSUE TITLE
Aimassist code problem

### ISSUE THREAD

**Issue by Kewun0** [DK22Pac/plugin-sdk#46]
okay so here is code i made and need help with
https://pastebin.com/RjwsmPEN

Im trying to do something 'alike' aimassist , but i cant aim the gun correctly at the nearest ped. The game sometimes even crashes
https://www.youtube.com/watch?v=7iXgxrbE7E0
Here you see how it looks weirdly
Could you help me out fixing the code? ;/

Also i have to tap the rightclick to shoot again ;/

**Comment by DK22Pac** [comment]
Did you check [this](https://github.com/DK22Pac/plugin-sdk/issues/41#issuecomment-325111130)?
Also, provide a full plugin code.

**Comment by Kewun0** [comment]
Yeah. I checked. But it aims at dead bodies, needs m_fHealth check or seomthing.
Anyway, the full code:https://pastebin.com/izEkrG3x

**Comment by Kewun0** [comment]
bump

**Comment by DK22Pac** [comment]
I have no idea how to make it working.
Have any CLEO/SCM code for this?

**Comment by Kewun0** [comment]
No :/

**Comment by Kewun0** [comment]
bump

**Comment by dex73r** [comment]
`gracz->m_apNearPeds[1]->m_fHealth != 0.0`
I am not really using the sdk, but from other gamehacking experiences, fHealth usually is 1 even if dead, have you considered debugging the health value before/after death?

**Comment by Kewun0** [comment]
i tried. 1.0 is same as 0.0
bump again ;(

**Comment by dex73r** [comment]
No. >= 1
Also tell us what are the health values when the unwanted target is dead

**Comment by Kewun0** [comment]
0.0 it is.

**Comment by dex73r** [comment]
https://github.com/DK22Pac/plugin-sdk/issues/46#issuecomment-325183816 you said that it aims at dead bodies, now it skips them? Solved then?

**Comment by Kewun0** [comment]
No. The game sometimes crashes and the aimassist is buggy. Sometimes it doesnt even aim and shoot as you see in video. Something like "aim bot"

**Comment by quiret** [comment]
No idea how you got this code working in the first place. This is the best I could fix it up to.

```cpp
#include "plugin_vc.h"
#include "game_vc/CPlayerPed.h"
#include "game_vc/CPlayerInfo.h"
#include "game_vc/common.h"

using namespace plugin;

static bool do_aim_assist = false;
static bool release_aim_assist = true;

class MyPlugin {
public:
    MyPlugin() {
        Events::gameProcessEvent += []() {
            CPed * gracz = FindPlayerPed();

            if ( release_aim_assist )
            {
                do_aim_assist = false;
                release_aim_assist = false;
            }

            if (KeyPressed('K'))
            {
                do_aim_assist = true;
                release_aim_assist = true;
            }
            else if (KeyPressed('I'))
            {
                do_aim_assist = !do_aim_assist;
            }

            if (do_aim_assist)
            {
                for ( size_t n = 0; n < _countof(gracz->m_apNearPeds) && n < gracz->m_nNumNearPeds; n++ )
                {
                    CPed *target = gracz->m_apNearPeds[n];

                    if ( target == NULL )
                        continue;

                    // Needs to pass security checks.
                    if ( target->m_fHealth > 1.0 && target->IsPedShootable() && target->IsVisible() )
                    {
                        gracz->m_pPointGunAt = target;
                        gracz->AimGun();
                        gracz->Attack();
                        gracz->ClearAttackByRemovingAnim();
                        return;
                    }
                }

                gracz->ClearAimFlag();
                gracz->ClearAttack();
                gracz->SetCurrentWeapon(0);
            }
        };
    }
} myPlugin;
```
I would highly appreciate it if someone could help Kev out with the shooting while aim assisting.

**Comment by ZeyadAhmed** [comment]
I tried to do something like that before i know about plugin-sdk i made something that make the nearest ped health = 0 and that make the nearest ped die, i made that through Cheat engine and another injectors then i relized something Nearest Ped Function gets the nearest peds in SPECIFIC range, idk if that right buut i saw that happen alot i mean if there are 5 peds : 3 in the RANGE,  and the others are out you will get in the array of bytes of length [5] that: (as example)
```0D 1E 2C 00 00`` and others people out of the range are 00, *also i dont know if that happens in the sdk too*
another thing that you have to put in mind, 1) Time 2)Movment
in time i mean that ASI take time to inject the function , i mean that
when you press the button that do the function, it shots behind the RUNNING ped because the variable took the value of the ped when you shot him the ped move more than the target value.
another thing is movement and that is based on time you can see in the last part that u shot the police because he was standing. also you will see another thing that is aim is not accurate or move like crazy becuase of changing of order of peds because maybe one be the first one then be the next then the first again
and i think that proves that crashing is that because of first array is ``00`` so you cant do the function to it because its NULL. so you have to make some conditions that avoid the NULL and i will try to write it soon :D

**Comment by Kewun0** [comment]
@quiret 

This code improves the aimbot alot, just needed to remove the clearimflag & clearattack & setcurrwep on the end
heres effects:
https://www.youtube.com/watch?v=HWwdNzAa-N0

**Comment by quiret** [comment]
Glad to have helped you, Kewun0! Feel free to share improvements on this issue and/or on our official [Discord server](https://discord.gg/X4H7ztF). We love hearing about ASI mods. :-)
