### ISSUE TITLE
IDB Exporting

### ISSUE THREAD

**Issue by Ankris** [DK22Pac/plugin-sdk#47]
Could you share the tool you used for exporting the functions? I'd like to push missing functions for GTA3 to the repo.

**Comment by DK22Pac** [comment]
Just added it to our "Tools" folder.

**Comment by Ankris** [comment]
Nice, but what about the classes/structs? Also, need I make manually the .h file?

**Comment by DK22Pac** [comment]
Yes, for new classes you should create new files.
We don't have a fully-automated tool, it was not a goal.

**Comment by Ankris** [comment]
Forgot to say, https://github.com/Ankris/plugin-sdk
I'm adding everything there

**Comment by DK22Pac** [comment]
Nice, but you forgot about function parameter names and return types.
You must provide this for every function, by checking & researching it in IDB.
We can allow only such function declarations.

**Comment by quiret** [comment]
I don't think that you were supposed to delete sa_sdk_func_gen.exe from the tools on your fork. If you are planing to open a pull request please reinstante that.

Other than that your additions and fixes look really interesting :-)

**Comment by Ankris** [comment]
@DK22Pac where? @quiret sometimes I have issues with git, so I had to remove it :/
