### ISSUE TITLE
LNK1181	cannot open input file 'plugin_vc.lib'

### ISSUE THREAD

**Issue by ZeyadAhmed** [DK22Pac/plugin-sdk#48]
I was writing a HelpMessage and while building got that error :cry: 
Code : [https://hastebin.com/unifiriviw.cpp](url)
Full Image: [https://cdn.discordapp.com/attachments/334256187530936320/355745457332420608/unknown.png](url)

**Comment by DK22Pac** [comment]
You need to build plugin_vc project in plugin-sdk solution.
First, create project/solution files for Visual Studio - launch `premake_`(Your VS version)`.bat` in plugin-sdk folder. This will generate plugin.sln file in plugin-sdk folder. Open it with Visual Studio.
Next, switch to Release mode and build plugin_vc project (RMB on project in solution explorer and "Build")

**Comment by quiret** [comment]
Also make sure to set the environment variables as described [here](https://github.com/DK22Pac/plugin-sdk/wiki/Environment-Variables-for-plugin-sdk).

**Comment by ZeyadAhmed** [comment]
oh , i didnt see your edited message xD, i will try now even after i added the variables it doesnt work do i have to use the wizard to generate it again?
also a small thing pls
Make a discord server for that plugin so we can talk about it + asks and disucss also there is github hook there to get notifications for new commits , please that will be nice addition :smile:

**Comment by quiret** [comment]
Let's talk in the plugin-sdk gitter.im page! :-)

https://gitter.im/plugin-sdk/Lobby

**Comment by ZeyadAhmed** [comment]
Thanks, Quiret i made the variables and it worked :) <3
Discord is faster and free + it have nice features and alot of people use it, is that bad idea ?

**Comment by quiret** [comment]
Not a bad idea at all. I am waiting for the opinion of other people.
