### ISSUE TITLE
Move tools to DK22Pac/plugin-sdk-tools repository

### ISSUE THREAD

**Issue by quiret** [DK22Pac/plugin-sdk#52]
We want to keep this repository as lightweight as possible so tools should be moved to this other repo. Or we could just host the source code to the tools there; it depends.

https://github.com/DK22Pac/plugin-sdk-tools

**Comment by DK22Pac** [comment]
Fixed in https://github.com/DK22Pac/plugin-sdk/commit/dd7b9133ee75b109e44fa15776ee293a65babfc9

Maybe we should move premake into 'tools' too?
