### ISSUE TITLE
Visual Studio pre-2015 Template Installation 

### ISSUE THREAD

**Issue by ZeyadAhmed** [DK22Pac/plugin-sdk#53]
As you can see here in this image https://cdn.discordapp.com/attachments/357966518463496192/359408325143822337/image.png
The Version is 2010 Professional

**Comment by DK22Pac** [comment]
We can't use plugin-sdk templates in VS2010-2013, because VisualC++ project templates are not available in these versions (in Viusal Stuido, they were introduced in VS2015).
