### ISSUE TITLE
Are there alternatives to RwIm2DRenderPrimitive?

### ISSUE THREAD

**Issue by yugecin** [DK22Pac/plugin-sdk#54]
I created something using `RwIm2DRenderPrimitive`, similar to what the GPS example does, but some people report that they don't see the lines.
Everyone that said it's not working is using integrated graphics (intel HD xxx), so I suppose some that might be the cause (same for me, I can't see them when I run SA using integrated graphics on my win8 laptop).

I'm mostly clueless about how to fix this, are there alternative ways to render primitives? Or can they do something to make it work for them (updating drivers etc)?

**Comment by DK22Pac** [comment]
Does GPS example wokr for you on your integrated graphics?

**Comment by yugecin** [comment]
Huh, it does.
I was using `rwPRIMTYPELINELIST` with no results, but using `rwPRIMTYPETRISTRIP` (like the gps example) does show something (after adding extra verts). Weird. Any ideas why?

**Comment by DK22Pac** [comment]
`rwPRIMTYPELINELIST` is used to draw lines, are you sure you want this?

**Comment by yugecin** [comment]
Yes lines is what I wanted. Lines work on my laptop when I use the dedicated gpu, but they don't show when I use the integrated gpu.

**Comment by quiret** [comment]
Maybe it doesn't support them. Did you know that devices do not have to support all primitive types?

**Comment by yugecin** [comment]
> Maybe it doesn't support them. Did you know that devices do not have to support all primitive types?
Didn't know, that's pretty interesting (and annoying). Luckily `rwPRIMTYPETRISTRIP` seems to work for now.
