### ISSUE TITLE
Create project error

### ISSUE THREAD

**Issue by XKangs** [DK22Pac/plugin-sdk#58]
I create a VC  ASI  project after i install it on VS 2017, then it throw a alter "异常来自 HRESULT: 0x80041FE2" (means "Exception from HRESULT: 0x80041FE2")

**Comment by gennariarmando** [comment]
Please make sure you have installed common tools for visual c+2017.

**Comment by XKangs** [comment]
I installed C++2017, but it doesn't work. same alter

**Comment by gennariarmando** [comment]
Try opening a default c++ project, if same warning appear, this means you didn't installed common tools correctly.

**Comment by DK22Pac** [comment]
Please open Visual Studio installer and show which components you have installed there (make a screen and upload here).

**Comment by XKangs** [comment]
![0](https://user-images.githubusercontent.com/17783163/32872148-23828f06-cac0-11e7-8e8a-99df4ed185fa.png)
![1](https://user-images.githubusercontent.com/17783163/32872150-2425dc60-cac0-11e7-8947-576aea18985a.png)
![2](https://user-images.githubusercontent.com/17783163/32872151-247ded6a-cac0-11e7-8e8a-70dd0cf3c503.png)
![34](https://user-images.githubusercontent.com/17783163/32872152-24d1635a-cac0-11e7-88ec-6aa075452dc4.png)
![56](https://user-images.githubusercontent.com/17783163/32872154-2527b62e-cac0-11e7-80e1-4cc3719ffe5e.png)
![789](https://user-images.githubusercontent.com/17783163/32872155-2566172a-cac0-11e7-9394-21ac617221a2.png)

**Comment by XKangs** [comment]
I can create a default c++ project successfully, but...here is the alert 
![alert](https://user-images.githubusercontent.com/17783163/32872202-6b822fa0-cac0-11e7-8f4f-9571122e322f.png)

**Comment by DK22Pac** [comment]
Can you please make same screenshots, but with English language?
Here's a guide on how to change the language:
https://docs.microsoft.com/ru-ru/visualstudio/install/install-visual-studio#step-6---install-language-packs-optional
