### ISSUE TITLE
SCMMod compatibility + merge with my project

### ISSUE THREAD

**Issue by Serabass** [DK22Pac/plugin-sdk#63]
Hello.
Have plugin-sdk a functionality to call SCM functions?
I have a repo which is broken now, but I collected a lot of useful addresses and SCM-functions you probably can include into plugin-sdk. It based on SCMMod by Spookie (you can Google it on Game Forums). Project developed only for VC.
I can contribute to a project and extend it when I understand how to use a plugin-sdk. 

Привет.
Имеет ли plugin-sdk функционал для работы с функциями SCM?
У меня есть репозиторий, который давно забросил, но собрал в нём массу полезных адресов и SCM-функций, которые вы могли бы себе забрать.
Он основана на SCMMod от Spookie (его можно найти его на игровых форумах). Проект разработан только для VC.
Я могу присоединиться к проекту и расширить его, когда пойму, как им пользоваться.

Link/Ссылка: https://github.com/Serabass/vc-magic

**Comment by ZeyadAhmed** [comment]
U can use ```Command<opcode>(arguments);```
Or ```Command<Commands::CommandName>(arguments); ```

**Comment by quiret** [comment]
Not sure if you know already but DK22Pac has uploaded a SCM example.

https://github.com/DK22Pac/plugin-sdk/blob/master/examples/ScriptCommands/ScriptCommands.cpp

Please check it out. Works for any GTA version. Does it help you?
