### ISSUE TITLE
GetModuleHandleExW error?

### ISSUE THREAD

**Issue by inanahammad** [DK22Pac/plugin-sdk#71]
While i try to build the paths a error pops up on codeblocks.In vs it works fine but only on cb.
here is a shot https://imgur.com/a/FwF51

**Comment by Zarig** [comment]
The minimum supported client for GetModuleHandleEx is Windows XP, so you need to set some defines to make it compile

define _WIN32_WINNT as 0x0501 or later
https://msdn.microsoft.com/en-us/library/aa383745(VS.85).aspx

**Comment by DK22Pac** [comment]
What's your mingw version? Where did you get it? Did you follow our guide when installing Code::Blocks? Did you make any changes into project config (because I see c++1z option there)?

**Comment by inanahammad** [comment]
@DK22pa it came with code blocks.And i didnt make any changes with project config.I was just testing with the C++1z.There were some more errors i am getting.Like the sprintf_s scope wasnt declared in this scope but after includeing the cstdio it got fixed.But now this occurs.

**Comment by DK22Pac** [comment]
@inanahammad, [install mingw-w64](https://github.com/DK22Pac/plugin-sdk/wiki/Installing-mingw-64) and [set it as a compiler in Code::Blocks](https://github.com/DK22Pac/plugin-sdk/wiki/Installing-development-environment-(IDE)#codeblocks).

**Comment by inanahammad** [comment]
thanks it helped

**Comment by quiret** [comment]
Closing this as inanahammad has been helped :-)
