### ISSUE TITLE
GPS dependencies Error - CFont

### ISSUE THREAD

**Issue by ArmynC** [DK22Pac/plugin-sdk#76]
Error	C3861	'SetAlignment': identifier not found
Error (active)	E0135	class "CFont" has no member "SetAlignment"	
Error (active)	E0135	class "CFont" has no member "SetProp"	
Error	C2039	'SetAlignment': is not a member of 'CFont'	
Error	C2039	'SetProp': is not a member of 'CFont'	
Error	C3861	'SetProp': identifier not found	GPS	

Possible Fix (main.cpp):

CFont::SetAlignment(ALIGN_CENTER); -> CFont::SetOrientation(ALIGN_CENTER);
CFont::SetProp(true); -> CFont::SetProportional(true);

After:
Error	LNK1181	cannot open input file 'plugin.lib'

**Comment by ZeyadAhmed** [comment]
Well, what game you are using?
In Vice City i cant find that function i think it exists in GTA 3 as i tested before.

**Comment by ZeyadAhmed** [comment]
these two functions doesn't exists in SA too

**Comment by ZeyadAhmed** [comment]
but there are two booleas
```
bool& CFont::m_bFontCentreAlign = *(bool *)0xC71A79;
bool& CFont::m_bFontRightAlign = *(bool *)0xC71A7A;
```
you can check for alignment.

**Comment by ArmynC** [comment]
Hmm.. I want to compile the SA_GPS (from example folder) and if I build it show: 
`Error	C3861	'SetAlignment': identifier not found
Error (active)	E0135	class "CFont" has no member "SetAlignment"
Error (active)	E0135	class "CFont" has no member "SetProp"
Error	C2039	'SetAlignment': is not a member of 'CFont'
Error	C2039	'SetProp': is not a member of 'CFont'
Error	C3861	'SetProp': identifier not found	GPS`

And I saw in CFont that these 2 functions have different 'names' so I changed them, now I have that error

**Comment by Crspy** [comment]
problem fixed, thank you for reporting.
