### ISSUE TITLE
LNK

### ISSUE THREAD

**Issue by ArmynC** [DK22Pac/plugin-sdk#77]
Before the git update I said that there was an error wich I did fix by myself but after that this appeared: 
`Error	LNK1181	cannot open input file 'plugin.lib'	`

After today's update it still give me that error (with an additional line):
`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"link.exe" exited with code 1181.	GPS	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	676	
Error	LNK1181	cannot open input file 'plugin.lib'	GPS	C:\Users\ArminC\Desktop\plugin-sdk-master\examples\GPS\LINK	1	
`

**Comment by ruhivuloglu** [comment]
Have you build plugin_sa or plugin_vc project? It should create the file.

**Comment by ArmynC** [comment]
So I downloaded the GIT, I did put the plugin sdk path into the installer.. I installed Visual Template then I generate it.. After that I did opened the gps project file inside example folder and I pressed BUILD

**Comment by DK22Pac** [comment]
So can you tell us why did you skip this step?
https://github.com/DK22Pac/plugin-sdk/wiki/Set-up-plugin-sdk#3-build-plugin-sdk-solutionworkspace

**Comment by ArmynC** [comment]
If I remember corectly I tried all the steps but there it gave me an error, not sure what and I thought that maybe I need to open only the example project.. anyway I tried now and the app compiled but with some errors: 

> Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory	plugin_sa	c:\users\arminc\desktop\plugin-sdk-master\shared\extensions\shader.h	12	
Warning	C4018	'>': signed/unsigned mismatch	plugin_vc	c:\users\arminc\desktop\plugin-sdk-master\shared\extensions\keycheck.cpp	33	
Warning	C4018	'>': signed/unsigned mismatch	plugin_iii	c:\users\arminc\desktop\plugin-sdk-master\shared\extensions\keycheck.cpp	33	

* I need to put dx sdk path in the installer ?

And if I try to compile the example gps:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'plugin.lib'	GPS	C:\Users\ArminC\Desktop\plugin-sdk-master\examples\GPS\LINK	1	

- It still give me that error (.. because above things?)
