### ISSUE TITLE
Constructor parameter for CPed::CPed is probably incorrect

### ISSUE THREAD

**Issue by Grovespaz** [DK22Pac/plugin-sdk#82]
[Itis currently documented as being modelIndex](https://github.com/DK22Pac/plugin-sdk/blob/a5c6bcbed99cbef3706b61de064233a6238d50ff/plugin_vc/game_vc/CPed.h#L587) but I suspect it should be pedType.
I hooked the constructor and I saw it being called with an even distribution of 4's and 5's and a lesser amount of 6's. That corresponds to Civmale, Civfemale and Cop respectively. They were definitely not the modelIndex's of the peds being spawned.

(I don't know if these files are auto-generated from another source, so I opened this issue first. 
If it's okay to just send a PR I will.)

**Comment by ZeyadAhmed** [comment]
Yes, It is.
![image](https://user-images.githubusercontent.com/19334375/47935731-22a5c880-dee4-11e8-9e08-a88a09f8554b.png)

**Comment by DK22Pac** [comment]
fixed
