### ISSUE TITLE
error: 'auto' parameter not permitted in this context

### ISSUE THREAD

**Issue by dvinhovhannisian** [DK22Pac/plugin-sdk#83]
Hi. I'm trying to compile a simple script but it gives me this error: 
error: 'auto' parameter not permitted in this context
The problem is in line 33 of PluginBase.h. It says `template<auto Func>` is incorrect. My compiler is GNU GCC compiler. Is there any solution for that?

**Comment by DK22Pac** [comment]
You need a compiler with C++17 support.

**Comment by dvinhovhannisian** [comment]
Thank you for immediate reply 😀 I'll try it

**Comment by dvinhovhannisian** [comment]
I solved my problem by updating the problem but now it says `cannot find -lplugin`.

**Comment by DK22Pac** [comment]
https://github.com/DK22Pac/plugin-sdk/wiki/Set-up-plugin-sdk#3-build-plugin-sdk-solutionworkspace

**Comment by dvinhovhannisian** [comment]
`error: 'GetModuleHandleExA' was not declared in this scope` at line 24 of plugin-sdk\shared\extensions\Paths.cpp

**Comment by dvinhovhannisian** [comment]
`error: 'GetModuleHandleExA' was not declared in this scope` at line 24 of C:\Users\dvinhovhannisian\plugin-sdk\shared\extensions\Paths.cpp and `error: 'GetModuleHandleExW' was not declared in this scope` at line 70 and to_string() is not a member of std at line 176 and 183

**Comment by dvinhovhannisian** [comment]
?

**Comment by DK22Pac** [comment]
Try to install Code::Blocks with mingw-w64 compiler, following our guides.
https://github.com/DK22Pac/plugin-sdk/wiki/Installing-development-environment-(IDE)#codeblocks

**Comment by dvinhovhannisian** [comment]
Thanks

**Comment by dvinhovhannisian** [comment]
Sorry for annoying you 😁

**Comment by dvinhovhannisian** [comment]
I did this https://github.com/DK22Pac/plugin-sdk/wiki/Set-up-plugin-sdk#3-build-plugin-sdk-solutionworkspace but again it says `cannot find -lplugin_d`

**Comment by dvinhovhannisian** [comment]
Thank you so much. I fixed my problems and now I can successfully compile my scripts 😀
