### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by yukani** [DK22Pac/plugin-sdk#86]
According to https://go.microsoft.com/fwlink/?linkid=2023588:

> The version of Visual C++ in Visual Studio 2019 preview 0 and later does not include support for creating code for Windows XP by using the v142 toolset.

SDK requires building with v141_xp toolset, so i think we cannot build plugins in 2019 version?

**Comment by DK22Pac** [comment]
You can build it if you have v141_xp toolset.
